# Generated by Django 3.2.3 on 2021-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=1, upload_to='images/%Y-%m-%d/'),
            preserve_default=False,
        ),
    ]
